import AppKit

struct LayoutFrameTarget: Equatable {
    let window: Window
    let topLeft: CGPoint?
    let size: CGSize?

    static func == (lhs: LayoutFrameTarget, rhs: LayoutFrameTarget) -> Bool {
        lhs.window.windowId == rhs.window.windowId &&
            lhs.topLeft == rhs.topLeft &&
            lhs.size == rhs.size
    }
}

@MainActor
final class LayoutTransaction {
    private(set) var targets: [UInt32: LayoutFrameTarget] = [:]

    func setFrame(_ window: Window, _ topLeft: CGPoint?, _ size: CGSize?) {
        targets[window.windowId] = LayoutFrameTarget(window: window, topLeft: topLeft, size: size)
    }
}

private struct AnimatedLayoutFrame {
    let target: LayoutFrameTarget
    let start: Rect
    let end: Rect
}

struct RejectedWindowSize: Equatable {
    let requested: CGSize
    let observed: CGSize
    let confirmations: Int
}

/// Learns when an application consistently clamps a requested AX size. Once a
/// refusal is confirmed, layout passes continue positioning the window but stop
/// resubmitting that impossible size until the requested size changes.
@MainActor
struct LayoutFrameAcceptanceTracker {
    private(set) var rejectedSizes: [UInt32: RejectedWindowSize] = [:]

    mutating func sizeToApply(windowId: UInt32, requested: CGSize?) -> CGSize? {
        guard let requested,
              let rejection = rejectedSizes[windowId],
              rejection.confirmations >= 2,
              sizesAreEffectivelyEqual(requested, rejection.requested)
        else { return requested }
        return nil
    }

    mutating func observe(windowId: UInt32, requested: CGSize, observed: CGSize) {
        if sizesAreEffectivelyEqual(requested, observed) {
            rejectedSizes.removeValue(forKey: windowId)
            return
        }

        if let previous = rejectedSizes[windowId],
           sizesAreEffectivelyEqual(previous.requested, requested),
           sizesAreEffectivelyEqual(previous.observed, observed)
        {
            rejectedSizes[windowId] = RejectedWindowSize(
                requested: requested,
                observed: observed,
                confirmations: min(previous.confirmations + 1, 2),
            )
        } else {
            rejectedSizes[windowId] = RejectedWindowSize(
                requested: requested,
                observed: observed,
                confirmations: 1,
            )
        }
    }
}

@MainActor
final class LayoutAnimator {
    static let shared = LayoutAnimator()

    private var animationTask: Task<Void, Never>?
    private var lastSubmittedTargets: [UInt32: LayoutFrameTarget]?
    private var acceptanceTracker = LayoutFrameAcceptanceTracker()
    private var generation: UInt = 0

    private init() {}

    func apply(_ transaction: LayoutTransaction, animated: Bool = true) {
        let targets = transaction.targets
        guard !targets.isEmpty else {
            generation &+= 1
            animationTask?.cancel()
            animationTask = nil
            lastSubmittedTargets = nil
            return
        }

        // AXPosition/AXSize notifications generated by our own frame writes can
        // arrive after the animation has finished. Keep the last submitted target,
        // not only the currently active one, so those notifications cannot start
        // the same animation forever. Any real tree, weight, workspace, or monitor
        // change produces a different target dictionary and is still applied.
        if animated && lastSubmittedTargets == targets { return }

        generation &+= 1
        let currentGeneration = generation
        animationTask?.cancel()
        lastSubmittedTargets = animated ? targets : nil

        let durationMs = config.layoutAnimationDurationMs
        let shouldAnimate = animated &&
            !isStartup &&
            durationMs > 0 &&
            !(config.layoutAnimationRespectReduceMotion && NSWorkspace.shared.accessibilityDisplayShouldReduceMotion)

        guard shouldAnimate else {
            applyImmediately(targets.values)
            animationTask = Task.startUnstructured { @MainActor [weak self] in
                guard let self else { return }
                await verifyAcceptedSizes(Array(targets.values), generation: currentGeneration)
                if generation == currentGeneration {
                    animationTask = nil
                }
            }
            return
        }

        animationTask = Task.startUnstructured { @MainActor [weak self] in
            guard let self else { return }
            await animate(Array(targets.values), durationMs: durationMs)
            if generation == currentGeneration {
                animationTask = nil
            }
        }
    }

    private func animate(_ targets: [LayoutFrameTarget], durationMs: Int) async {
        var animatedFrames: [AnimatedLayoutFrame] = []

        for originalTarget in targets {
            guard !Task.isCancelled else { return }
            let target = LayoutFrameTarget(
                window: originalTarget.window,
                topLeft: originalTarget.topLeft,
                size: acceptanceTracker.sizeToApply(
                    windowId: originalTarget.window.windowId,
                    requested: originalTarget.size,
                ),
            )
            guard let start = try? await target.window.getAxRect(.cancellable) else {
                target.window.setAxFrame(target.topLeft, target.size)
                continue
            }

            let end = Rect(
                topLeftX: target.topLeft?.x ?? start.topLeftX,
                topLeftY: target.topLeft?.y ?? start.topLeftY,
                width: target.size?.width ?? start.width,
                height: target.size?.height ?? start.height,
            )

            guard !framesAreEffectivelyEqual(start, end) else { continue }

            // Cross-monitor and workspace transitions should not travel through other
            // desktops. They snap to their destination; only local reflows animate.
            let destinationMonitor = end.center.monitorApproximation
            guard destinationMonitor.rect.contains(start.center) else {
                target.window.setAxFrame(target.topLeft, target.size)
                continue
            }

            animatedFrames.append(AnimatedLayoutFrame(target: target, start: start, end: end))
        }

        guard !Task.isCancelled else { return }

        if animatedFrames.isEmpty {
            await verifyAcceptedSizes(targets, generation: generation)
            return
        }

        let duration = Double(durationMs) / 1000
        let startedAt = ProcessInfo.processInfo.systemUptime

        while !Task.isCancelled {
            let elapsed = ProcessInfo.processInfo.systemUptime - startedAt
            let linearProgress = min(max(elapsed / duration, 0), 1)
            let easedProgress = easeOutCubic(linearProgress)

            for frame in animatedFrames {
                let rect = interpolate(from: frame.start, to: frame.end, progress: easedProgress)
                frame.target.window.setAxFrame(rect.topLeftCorner, rect.size)
            }

            if linearProgress >= 1 { break }
            try? await Task.sleep(for: .milliseconds(16))
        }

        guard !Task.isCancelled else { return }
        for frame in animatedFrames {
            frame.target.window.setAxFrame(frame.target.topLeft, frame.target.size)
        }
        await verifyAcceptedSizes(targets, generation: generation)
    }

    private func applyImmediately(_ targets: Dictionary<UInt32, LayoutFrameTarget>.Values) {
        for target in targets {
            target.window.setAxFrame(
                target.topLeft,
                acceptanceTracker.sizeToApply(windowId: target.window.windowId, requested: target.size),
            )
        }
    }

    private func verifyAcceptedSizes(_ targets: [LayoutFrameTarget], generation expectedGeneration: UInt) async {
        guard !targets.isEmpty else { return }
        // Take two samples after AX has processed the final write. Requiring the
        // same mismatch twice distinguishes a real application constraint from
        // a delayed notification without waiting for another layout transaction.
        for _ in 0 ..< 2 {
            try? await Task.sleep(for: .milliseconds(34))
            guard !Task.isCancelled, generation == expectedGeneration else { return }
            for target in targets {
                guard !Task.isCancelled, generation == expectedGeneration else { return }
                guard let requested = target.size,
                      let actual = try? await target.window.getAxRect(.cancellable)?.size
                else { continue }
                acceptanceTracker.observe(
                    windowId: target.window.windowId,
                    requested: requested,
                    observed: actual,
                )
            }
        }
    }
}

private func easeOutCubic(_ progress: Double) -> Double {
    1 - pow(1 - progress, 3)
}

private func interpolate(from start: Rect, to end: Rect, progress: Double) -> Rect {
    func value(_ start: CGFloat, _ end: CGFloat) -> CGFloat {
        start + (end - start) * CGFloat(progress)
    }

    return Rect(
        topLeftX: value(start.topLeftX, end.topLeftX),
        topLeftY: value(start.topLeftY, end.topLeftY),
        width: value(start.width, end.width),
        height: value(start.height, end.height),
    )
}

private func framesAreEffectivelyEqual(_ lhs: Rect, _ rhs: Rect) -> Bool {
    abs(lhs.topLeftX - rhs.topLeftX) < 0.5 &&
        abs(lhs.topLeftY - rhs.topLeftY) < 0.5 &&
        abs(lhs.width - rhs.width) < 0.5 &&
        abs(lhs.height - rhs.height) < 0.5
}

private func sizesAreEffectivelyEqual(_ lhs: CGSize, _ rhs: CGSize) -> Bool {
    abs(lhs.width - rhs.width) < 1 && abs(lhs.height - rhs.height) < 1
}
