import AppKit
import Common

private struct SmoothWorkspaceLayoutSnapshot {
    let monitorName: String
    let monitorIsHorizontal: Bool
    let style: SmoothLayoutStyle
    let windowIds: [UInt32]

    func matches(_ other: SmoothWorkspaceLayoutSnapshot) -> Bool {
        monitorName == other.monitorName &&
            monitorIsHorizontal == other.monitorIsHorizontal &&
            style == other.style &&
            windowIds == other.windowIds
    }

    func canReuseLayout(
        monitorName: String,
        monitorIsHorizontal: Bool,
        style: SmoothLayoutStyle,
        windowIds: [UInt32],
    ) -> Bool {
        self.monitorName == monitorName &&
            self.monitorIsHorizontal == monitorIsHorizontal &&
            self.style == style &&
            self.windowIds.toSet() == windowIds.toSet()
    }
}

@MainActor
private var smoothWorkspaceLayoutSnapshots: [String: SmoothWorkspaceLayoutSnapshot] = [:]

@MainActor
private var isReconcilingSmoothWorkspaceLayouts = false

@MainActor
func invalidateSmoothWorkspaceLayoutSnapshots() {
    smoothWorkspaceLayoutSnapshots = [:]
}

@MainActor
func reconcileSmoothWorkspaceLayouts() {
    guard !isReconcilingSmoothWorkspaceLayouts else { return }
    isReconcilingSmoothWorkspaceLayouts = true
    defer { isReconcilingSmoothWorkspaceLayouts = false }

    enforceSmoothMonitorTileLimits()

    let existingWorkspaceNames = Workspace.all.map(\.name).toSet()
    smoothWorkspaceLayoutSnapshots = smoothWorkspaceLayoutSnapshots.filter { existingWorkspaceNames.contains($0.key) }

    for workspace in Workspace.all {
        let root = workspace.rootTilingContainer
        let currentWindows = root.allLeafWindowsRecursive
        guard !currentWindows.isEmpty else {
            smoothWorkspaceLayoutSnapshots.removeValue(forKey: workspace.name)
            continue
        }

        let monitor = workspace.workspaceMonitor
        let profile = SmoothLayoutSettingsStore.shared.profile(for: monitor)
        guard profile.enabled else {
            smoothWorkspaceLayoutSnapshots.removeValue(forKey: workspace.name)
            continue
        }

        let style = profile.style(for: currentWindows.count)
        let previous = smoothWorkspaceLayoutSnapshots[workspace.name]
        let currentWindowIds = currentWindows.map(\.windowId)
        let monitorIsHorizontal = monitor.width >= monitor.height

        // A swap, focus change, or manual resize must not trigger a complete
        // rebuild. Besides feeling abrupt, rebuilding in response to AX events
        // generated by that same rebuild can create a feedback loop. Track the
        // new DFS order and only rebuild when membership or profile changes.
        if previous?.canReuseLayout(
            monitorName: monitor.name,
            monitorIsHorizontal: monitorIsHorizontal,
            style: style,
            windowIds: currentWindowIds,
        ) == true {
            smoothWorkspaceLayoutSnapshots[workspace.name] = SmoothWorkspaceLayoutSnapshot(
                monitorName: monitor.name,
                monitorIsHorizontal: monitorIsHorizontal,
                style: style,
                windowIds: currentWindowIds,
            )
            continue
        }

        let orderedWindows = orderWindows(currentWindows, preserving: previous)
        let snapshot = SmoothWorkspaceLayoutSnapshot(
            monitorName: monitor.name,
            monitorIsHorizontal: monitorIsHorizontal,
            style: style,
            windowIds: orderedWindows.map(\.windowId),
        )

        guard previous?.matches(snapshot) != true else { continue }
        workspace.applySmoothLayout(style, to: orderedWindows, monitor: monitor)
        smoothWorkspaceLayoutSnapshots[workspace.name] = snapshot
    }
}

@MainActor
private func enforceSmoothMonitorTileLimits() {
    let persistentOrder = Dictionary(
        uniqueKeysWithValues: config.persistentWorkspaces.enumerated().map { ($0.element, $0.offset) },
    )
    let groupedWorkspaces = Dictionary(grouping: Workspace.all) { $0.workspaceMonitor.name }

    for (_, unsortedWorkspaces) in groupedWorkspaces {
        let workspaces = unsortedWorkspaces.sorted {
            (persistentOrder[$0.name] ?? Int.max, $0.name) <
                (persistentOrder[$1.name] ?? Int.max, $1.name)
        }
        guard let monitor = workspaces.first?.workspaceMonitor else { continue }
        let profile = SmoothLayoutSettingsStore.shared.profile(for: monitor)
        guard profile.enabled else { continue }

        let limit = profile.tileLimit
        var counts = Dictionary(
            uniqueKeysWithValues: workspaces.map { ($0.name, $0.rootTilingContainer.allLeafWindowsRecursive.count) },
        )

        for source in workspaces {
            let sourceWindows = source.rootTilingContainer.allLeafWindowsRecursive
            guard sourceWindows.count > limit else { continue }

            for window in sourceWindows.dropFirst(limit) {
                guard let target = workspaces.first(where: {
                    $0 !== source && (counts[$0.name] ?? 0) < limit
                }) else { break }

                window.bind(
                    to: target.rootTilingContainer,
                    adaptiveWeight: WEIGHT_AUTO,
                    index: INDEX_BIND_LAST,
                )
                counts[source.name, default: sourceWindows.count] -= 1
                counts[target.name, default: 0] += 1
            }
        }
    }
}

private func orderWindows(
    _ currentWindows: [Window],
    preserving previous: SmoothWorkspaceLayoutSnapshot?,
) -> [Window] {
    guard let previous else { return currentWindows }

    let windowsById = Dictionary(uniqueKeysWithValues: currentWindows.map { ($0.windowId, $0) })
    let existingWindows = previous.windowIds.compactMap { windowsById[$0] }
    let previousIds = previous.windowIds.toSet()
    let newlyAddedWindows = currentWindows.filter { !previousIds.contains($0.windowId) }
    return existingWindows + newlyAddedWindows
}

extension Workspace {
    @MainActor
    fileprivate func applySmoothLayout(_ requestedStyle: SmoothLayoutStyle, to windows: [Window], monitor: MonitorInfo) {
        guard !windows.isEmpty else { return }

        let root = rootTilingContainer
        let previouslyFocusedWindow = focus.windowOrNil?.takeIf { windows.contains($0) }

        // Detach leaves first, then discard the now-empty container hierarchy.
        // The workspace root itself stays alive so commands holding a reference to
        // it remain valid during this single coordinated layout transaction.
        for window in windows where window.isBound {
            window.unbindFromParent()
        }
        for child in root.children {
            child.unbindFromParent()
        }

        for window in windows { window.isFullscreen = false }

        let style: SmoothLayoutStyle = windows.count == 1
            ? .fullscreen
            : requestedStyle == .fullscreen ? .columns : requestedStyle

        switch style {
            case .fullscreen:
                configureRoot(root, orientation: monitor.width >= monitor.height ? .h : .v)
                bindSmoothWindow(windows[0], to: root)
                windows[0].isFullscreen = true

            case .columns:
                configureRoot(root, orientation: .h)
                windows.forEach { bindSmoothWindow($0, to: root) }

            case .rows:
                configureRoot(root, orientation: .v)
                windows.forEach { bindSmoothWindow($0, to: root) }

            case .dwindle:
                configureRoot(root, orientation: .h)
                buildDwindle(windows, in: root, orientation: .h)

            case .verticalPairs:
                configureRoot(root, orientation: .v)
                buildRows(windows, in: root, columnsPerRow: 2)

            case .grid:
                configureRoot(root, orientation: .v)
                let aspectRatio = max(Double(monitor.width / monitor.height), 0.1)
                let columnCount = min(
                    windows.count,
                    max(1, Int(ceil(sqrt(Double(windows.count) * aspectRatio)))),
                )
                buildRows(windows, in: root, columnsPerRow: columnCount)
        }

        previouslyFocusedWindow?.markAsMostRecentChild()
    }
}

@MainActor
private func configureRoot(_ root: TilingContainer, orientation: Orientation) {
    root.layout = .tiles
    root.changeOrientation(orientation)
}

@MainActor
private func bindSmoothWindow(_ window: Window, to parent: TilingContainer) {
    window.bind(to: parent, adaptiveWeight: WEIGHT_AUTO, index: INDEX_BIND_LAST)
}

@MainActor
private func buildDwindle(_ windows: ArraySlice<Window>, in parent: TilingContainer, orientation: Orientation) {
    guard let first = windows.first else { return }
    let remaining = windows.dropFirst()

    bindSmoothWindow(first, to: parent)
    guard !remaining.isEmpty else { return }

    if remaining.count == 1 {
        bindSmoothWindow(remaining.first.orDie(), to: parent)
        return
    }

    let tail = TilingContainer(
        parent: parent,
        adaptiveWeight: WEIGHT_AUTO,
        orientation.opposite,
        .tiles,
        index: INDEX_BIND_LAST,
    )
    buildDwindle(remaining, in: tail, orientation: orientation.opposite)
}

@MainActor
private func buildDwindle(_ windows: [Window], in parent: TilingContainer, orientation: Orientation) {
    buildDwindle(windows[...], in: parent, orientation: orientation)
}

@MainActor
private func buildRows(_ windows: [Window], in root: TilingContainer, columnsPerRow: Int) {
    var index = 0
    while index < windows.count {
        let end = min(index + columnsPerRow, windows.count)
        let rowWindows = windows[index ..< end]

        if rowWindows.count == 1 {
            bindSmoothWindow(rowWindows.first.orDie(), to: root)
        } else {
            let row = TilingContainer(
                parent: root,
                adaptiveWeight: WEIGHT_AUTO,
                .h,
                .tiles,
                index: INDEX_BIND_LAST,
            )
            rowWindows.forEach { bindSmoothWindow($0, to: row) }
        }
        index = end
    }
}
